name: Release Notify

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_name:
        description: Release title to post
        required: true
      release_body:
        description: Release notes body to post
        required: true
      release_html_url:
        description: Release URL to link in Discord
        required: false

jobs:
  to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Push notification to Discord webhook
        uses: SethCohen/github-releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          release_name: ${{ inputs.release_name }}
          release_body: ${{ inputs.release_body }}
          release_html_url: ${{ inputs.release_html_url }}
          avatar_url: "https://github.com/medylme/osu-twitchbot/blob/cf0cdad96403d1b9bcd0ecbf427fa48bb8652e18/assets/icon.png?raw=true"
          color: "15418782"
          username: "osu-twitchbot"
          content: "New release published! *Existing installations will auto-update.*"
          footer_title: "Changelog"
          footer_timestamp: true
          reduce_headings: true
